package com.example.manejodemensajes.Mensajes

enum class Errores {
    NO_HAY_RED,
    ERROR_GUARDAR,
    EXITO_SUCCES,
    CAMPO_VACIO,
    SE_ENVIO_NUB,
    ERROR_SOLICITU_HTTP,
    BIENVENIDA,
    PERMISOS,
    MANTENIMIENTO,
    ERROR_FALTACARACTERES,
    ERROR_ESPERAR,
    ERROR_LICENCIAINSERTADA

}